# https://upptime.js.org/docs/configuration

owner: uwutube
repo: status

sites:
  - name: uwutube web
    url: https://uwutube.co/

assignees:
  - xezno

status-website:
  cname: status.uwutube.co
  logoUrl: https://uwutube.co/images/logo.svg
  name: uwutube status
  navbar:
    - title: status
      href: /
    - title: uwutube
      href: https://uwutube.co/

commitMessages:
  commitAuthorName: "uwutube bot"
  commitAuthorEmail: "76650104+uwutube-bot@users.noreply.github.com"
