# https://upptime.js.org/docs/configuration

owner: uwutube
repo: status

# Add your sites here
sites:
  - name: uwutube web
    url: https://uwutube.co/

status-website:
  cname: status.uwutube.co
  logoUrl: https://uwutube.co/img/logo.svg
  name: uwutube status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
